spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 2023@@RootUserMySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      secret-key: 3373367638792F423F4528482B4D6251655468576D5A7134743777217A244326
      expiration: 3600
      refresh-token:
        expiration: 604800
